CREATE TABLE IF NOT EXISTS books (
    id          BIGSERIAL PRIMARY KEY NOT NULL,
    title       CHAR(255) NOT NULL DEFAULT '',
    isbn        CHAR(100) NOT NULL DEFAULT '',
    author      CHAR(255) NOT NULL DEFAULT '',
    is_deleted  BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);